[build]
builder = "RAILPACK"
rootDirectory = "backend"
buildCommand = "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "gunicorn app:app"
sleepApplication = false
useLegacyStacker = false
multiRegionConfig = {"asia-southeast1-eqsg3a":{"numReplicas":1}}
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
